name: secondfyp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  auto_size_text: ^3.0.0
  firebase_storage: any
  image_picker: any
  intl: ^0.19.0
  pdf: ^3.10.8

  printing: ^5.12.0
  fl_chart: ^0.36.0
  firebase_auth: ^4.16.0
  cached_network_image: ^3.3.1
  firebase_messaging: ^14.7.10
  another_flutter_splash_screen: ^1.2.1
  sendgrid_mailer: ^0.1.3
  mailer: ^6.1.1
  flutter_local_notifications: ^17.2.1+1
  animated_bottom_navigation_bar: ^1.3.3
  flutter_image_compress: ^2.0.0
dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: ^0.13.1


flutter_icons:
  android: true
  image_path: "assets/lc.png"
flutter: 
  uses-material-design: true

  assets:
    - assets/