// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvNHZJm9btJqtOfzfwK2QvolKJQTjmiQM',
    appId: '1:167199885657:web:d62a95af2bff9e447ea448',
    messagingSenderId: '167199885657',
    projectId: 'fypmy-ef96d',
    authDomain: 'fypmy-ef96d.firebaseapp.com',
    databaseURL: 'https://fypmy-ef96d-default-rtdb.firebaseio.com',
    storageBucket: 'fypmy-ef96d.appspot.com',
    measurementId: 'G-NNNE39QPWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_skVq8ewX9b5wwdFmSXBf0D8de7jkMsg',
    appId: '1:167199885657:android:590a4d039ed332967ea448',
    messagingSenderId: '167199885657',
    projectId: 'fypmy-ef96d',
    databaseURL: 'https://fypmy-ef96d-default-rtdb.firebaseio.com',
    storageBucket: 'fypmy-ef96d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCp36NeNU6A7ZcW2tmG7XJimYYe-lpf90',
    appId: '1:167199885657:ios:9efaf0889412067b7ea448',
    messagingSenderId: '167199885657',
    projectId: 'fypmy-ef96d',
    databaseURL: 'https://fypmy-ef96d-default-rtdb.firebaseio.com',
    storageBucket: 'fypmy-ef96d.appspot.com',
    iosBundleId: 'com.secondfyp.secondfyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCp36NeNU6A7ZcW2tmG7XJimYYe-lpf90',
    appId: '1:167199885657:ios:f3e40ff144c9177f7ea448',
    messagingSenderId: '167199885657',
    projectId: 'fypmy-ef96d',
    databaseURL: 'https://fypmy-ef96d-default-rtdb.firebaseio.com',
    storageBucket: 'fypmy-ef96d.appspot.com',
    iosBundleId: 'com.secondfyp.secondfyp.RunnerTests',
  );
}
